# Name of workflow
name: CI

# Want action to happen on "push" to any branch
on: [push]

# list of jobs to run against application
jobs: 
  sast_scan: 
    name: Run Bandit Scan
    runs-on: ubuntu-latest       # Image/Runtime Environment to run the job on

    steps:
    - name: Checkout code
      uses: actions/checkout@v2   # Github action that will checout our code. 

    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -r .

